version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  jobs:
    pre_build:
      - curl -Ls https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.cargo/bin:$PATH"
      - uv sync

    build:
      - cd docs
      - make html

sphinx:
  configuration: docs/source/conf.py
