version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  jobs:
    pre_build:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
      - uv sync

    build:
      html:
        - cd docs
        - make html

sphinx:
  configuration: docs/source/conf.py
